# Site settings
url: "https://www.mpri.me"
name: 'Marco Primi'
subname: 'a.k.a. mprime'
subsubname: 'ğŸŒ Dependable Distributed Systems <br /> ğŸŒ± Organic Social Networks <br /> ğŸ´â€â˜ ï¸ Hack The Planet!<br /> ğŸŒˆ Game-B is ON!'

# Meta
title: "Marco Primi"
description: "Marco Primi's Homepage"

# Links
github_username:  mprimi
linkedin_username: marcoprimi
soundcloud_username:  djallyoucaneat
notes_url: "https://notes.mpri.me"
email: marco@mpri.me
public_key_url: "marco.txt"
scholar_url: "https://scholar.google.com/citations?user=IFUk6roAAAAJ"

# Images
avatar: yes
avatar_img_path: "imgs/avatar.jpg"
front_img: yes
front_img_path: "imgs/background.jpg"
favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["LICENSE", README.md]
